### ISSUE TITLE
Which static site generator?

### ISSUE THREAD

**Issue by dkua** [HackHub/hackhub.ca#2]
Should we stick with what we know (Pelican) or try something new? Like Hugo which is written in Go. [https://github.com/spf13/hugo](https://github.com/spf13/hugo)

Also who wants to set it all up? :P 

@wmak ?
@olanmatt ?

**Comment by olanmatt** [comment]
My vote is for Pelican.

**Comment by dkua** [comment]
Pelican would be easier to maintain just due to previous experience and that anyone we pass it onto know Python.

Soooo what template should we use and who wants to set it up

**Comment by olanmatt** [comment]
The template will be temporary right? We should put together a custom Pelican theme.

**Comment by dkua** [comment]
The template can be temporary or permanent. Whatever good design we come to a consensus too.

We might wanna look at other student hacker group sites like [http://hackmcgill.com/](http://hackmcgill.com/) and [http://www.hackeracademy.org/](http://www.hackeracademy.org/).

Also I wonder what's the significance of the bird logo of Hack McGill. It does make good stickers.

**Comment by dkua** [comment]
Hey @wmak please check out the hackmcgill site above to see a site with the kind of resources I'd like in the site. Also if you've picked a generator please close this issue.

**Comment by wmak** [comment]
Going with Pelican. Also will take a look at Hackmcgill thanks @dkua.
